name: Docker image CD

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the image
        run: |
          docker buildx build --push \
            --tag grobut939/ghostfolio:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
